apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5000
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-login-protector-dev
product: kind
kubernetesVersion: v1.30.0
registry: ctlptl-registry
