apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      securityContext: null
      containers:
        - command:
            - /login-protector
          args: null
          name: manager
          securityContext: null
