name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make lint
    - run: make test-e2e
  test-teleport:
    name: E2E Test with Teleport
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: ./.github/actions/aqua
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: make setup-teleport-cli
      - run: make test-teleport
