name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: The name of the tag to release (X.Y.Z)
jobs:
  release:
    name: Release login-protector
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
      - name: Validate inputs
        run: |
          if [[ ! ${{ inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Please use X.Y.Z"
            exit 1
          fi
          if git rev-parse v${{ inputs.tag }} >/dev/null 2>&1; then
              echo "Tag v${{ inputs.tag }} already exists"
              exit 1
          fi
      - uses: ./.github/actions/aqua
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push login-protector
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/cybozu-go/login-protector:${{ inputs.tag }},ghcr.io/cybozu-go/login-protector:latest
          target: login-protector
      - name: Build and Push local-session-tracker
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/cybozu-go/local-session-tracker:${{ inputs.tag }},ghcr.io/cybozu-go/local-session-tracker:latest
          target: local-session-tracker
      - name: Setup Git Config
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Generate install.yaml and push tag
        shell: bash -xe {0}
        run: |
          PROTECTOR_IMG=ghcr.io/${{ github.repository }}:${{ inputs.tag }} make build-installer
          git checkout config/manager/kustomization.yaml
          if ! git diff --exit-code --quiet; then
            git add ./dist/install.yaml
            git commit -m "Generate install.yaml for login-protector v${{ inputs.tag }}"
            git push
          fi
          git tag -a v${{ inputs.tag }} -m "Release login-protector v${{ inputs.tag }}"
          git push origin v${{ inputs.tag }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ inputs.tag }} --title "Release v${{ inputs.tag }}" --generate-notes
          gh release upload v${{ inputs.tag }} ./dist/install.yaml --clobber
